on:
  push:
    branches:
      - PR_Integration
name: Code checker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@v1
      - run: flutter doctor
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk -t lib/main_prod.dart --flavor=prod
#      - uses: actions/upload-artifact@master
#        with:
#          name: app-release
#          path: build/app/outputs/flutter-apk/app-release.apk
#      - uses: geekyeggo/delete-artifact@v1
#        with:
#          name: app-release
